name: Install / Update
on:
  push:
    branches:
      - master
      - dev
      - window_support
jobs:
  TestInstallation:
    name: "Run installation script on ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Check marvinette is launch-able
        run: |
          sudo php install.php
          which marvinette
          file /usr/bin/marvinette