name: Install / Update
on:
  push:
    branches:
      - master
      - dev
      - window_support
jobs:
  InstallationTest:
    name: "Run installation script on ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install
        run: php install.php
      - name: Check marvinette is launch-able (Linux)
        if:  ${{ matrix.name == 'Linux'}}
        run: |
          which marvinette
          file $HOME/bin/marvinette
          marvinette --help
      - name: Check marvinette is launch-able (Windows)
        if:  ${{ matrix.name == 'Windows'}}
        shell: bash
        run: |
          export PATH=$PATH:$CWD
          cd ..
          cd ..
          which marvinette
          marvinette --help