name: Install / Update
on:
  push:
    branches:
      - master
      - dev
      - window_support
jobs:
  InstallationTest:
    name: "Run installation script on ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install and Check marvinette is launch-able (Linux)
        if:  ${{ matrix.name == 'Linux'}}
        run: |
          sudo php install.php
          which marvinette
          marvinette --help
      - name: Install and check marvinette is launch-able (Windows)
        if:  ${{ matrix.name == 'Windows'}}
        run: |
          php install.php
          $env:Path += ";D:\a\Marvinette\Marvinette"
          marvinette --help
