name: Tests
on:
  workflow_run:
    workflows: ["Unit Tests"]
    branches: [master, dev, window_test_workflow]
    types: 
      - completed

jobs:
  StaticAnalysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
           fetch-depth: 0
      - name: Download coverage files from unit tests' job
        uses: actions/download-artifact@v2
        with:
          name: coverage_files
      - name: Fix Coverage File Path
        run: |
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' test-report.xml
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage-report.clover
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          