name: Tests
on:
  push:
    branches:
      - master
      - dev
      - workflow

jobs:
  TestsExecution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
           fetch-depth: 0
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug
      - name: Get dependencies
        uses: php-actions/composer@v6
        with:
          args: require phpunit/phpunit ^9
      - name: Execute unit tests
        run: |
          php -v
          mkdir tmp
          ./vendor/bin/phpunit tests --testdox --coverage-html tests/coverage --coverage-filter src
          ./vendor/bin/phpunit tests --testdox --coverage-clover=coverage-report.clover --log-junit=test-report.xml --coverage-filter src
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          