name: Tests
on:
  push:
    branches:
      - master
      - dev

jobs:
  TestsExecution:
    runs-on: ubuntu-latest
    container: arthichaud/ci_docker_image:latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
           fetch-depth: 0
      - name: Install PHP 7.4
        run: |
          sudo apt -y install lsb-release apt-transport-https ca-certificates 
          sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
          echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
          sudo apt update
          sudo apt-get -y install php7.4-common php7.4-xml php7.4 php7.4-mbstring php-xdebug
          php --ini
          composer require --dev phpunit/phpunit ^9
      - name: Execute unit tests
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug
        run: |
          php -v
          mkdir tmp
          ./vendor/bin/phpunit tests --testdox --coverage-html tests/coverage --coverage-filter src
          ./vendor/bin/phpunit tests --testdox --coverage-clover=coverage-report.clover --log-junit=test-report.xml --coverage-filter src
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          