name: Unit Tests
on:
  push:
    branches:
      - master
      - dev
      - workflow

jobs:
  TestsExecution:
    runs-on: ubuntu-latest
    container: arthichaud/ci_docker_image:latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: compile unit tests
        run: |
          sudo apt update
          sudo apt-get install php7.4-common php7.4-xml php7.4
          php --ini
          composer require --dev phpunit/phpunit ^9
          ./vendor/bin/phpunit tests --testdox --coverage-html tests/coverage --coverage-filter src