name: Unit Tests
on:
  push:
    branches:
      - master
      - dev
      - window_support

jobs:
  TestsExecution:
    name: "Run unit tests on ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
          - os: windows-latest
            name: Windows
    steps:
      - uses: actions/checkout@v2.3.4
        with:
           fetch-depth: 0
      - name: Setup PHP with Xdebug
        if: matrix.name == 'Linux'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: xdebug
      - name: Get dependencies
        uses: php-actions/composer@v6
      - name: Execute unit tests
        run: |
          mkdir tmp
          ./vendor/bin/phpunit tests --testdox --coverage-clover=coverage-report.clover --log-junit=test-report.xml --coverage-filter src
      - name: Upload coverage files
        if: matrix.name == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: coverage_files
          path: |
            test-report.xml
            coverage-report.clover
